MODEL:
    PRETRAIN_CHOICE: 'self'
    PRETRAIN_PATH: '/home/gongyou.zyq/reid_pytorch_unsup/resnet50_model_60.pth'
    # PRETRAIN_CHOICE: 'imagenet'
    # PRETRAIN_PATH: '/home/gongyou.zyq/.torch/models/resnet50-19c8e357.pth'

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 1.0 # random erasing

TGT_UNSUPDATA:
  CLUSTER_TOPK: 700
  CLUSTER_DIST_THRD: 0.25
  PSOLABEL_PERIOD: 3
  NAMES: ('ourapi')
  TRAIN_DIR: ('/home/gongyou.zyq/datasets/Refined_DukeMTMC_reID')
  SAMPLER_UNIFORM: 'id' # img or id
  NUM_INSTANCE: 8
  CLS_LR: 0.08

TGT_SUPDATA:
  NAMES: ('ourapi')
  TRAIN_DIR: ('/home/gongyou.zyq/datasets/Refined_DukeMTMC_reID')
  SAMPLER_UNIFORM: 'id' # img or id
  NUM_INSTANCE: 36
  NUM_POS_INSTANCE: 4

SRC_DATA:
  NAMES: ('ourapi')
  TRAIN_DIR: ('/home/gongyou.zyq/datasets/Corrected_Market1501')
  SAMPLER_UNIFORM: 'id' # img or id
  NUM_INSTANCE: 8

VAL_DATA:
  NAMES: ('ourapi')
  TRAIN_DIR: ('/home/gongyou.zyq/datasets/Refined_DukeMTMC_reID')

DATALOADER:
  NUM_WORKERS: 4
  SAMPLER_PROB: [0.,0.,1.0] # src, tgt_sup, tgt_unsup
  IMS_PER_BATCH: 48

LOSS:
  LOSS_TYPE: ['trp_cls','trp','trp_cls'] # src, tgt_sup, tgt_unsup
  LOSS_WEIGHTS: [0.0,0.0,1.0] # src, tgt_sup, tgt_unsup
  IF_LABELSMOOTH: 'on'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 61
  BASE_LR: 0.08
  WEIGHT_DECAY: 0.

  STEPS: [24, 48]

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 30
  EVAL_PERIOD: 60

TEST:
  IMS_PER_BATCH: 64
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "./log/market2duke"


